// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXNJkZ-FBDem8jqXmrlRP79QlFGKbO1WI',
    appId: '1:67132721194:web:9fd2ae307107e80d739b53',
    messagingSenderId: '67132721194',
    projectId: 'surveillance-app-ef466',
    authDomain: 'surveillance-app-ef466.firebaseapp.com',
    databaseURL: 'https://surveillance-app-ef466-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'surveillance-app-ef466.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCirY5X3mTGR91jKrkbKUIY0XoTRigUKDM',
    appId: '1:67132721194:android:2c95e2a11303330d739b53',
    messagingSenderId: '67132721194',
    projectId: 'surveillance-app-ef466',
    databaseURL: 'https://surveillance-app-ef466-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'surveillance-app-ef466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5T8hR8SXNTAmeUJwwlgBijvTlNLb-e6A',
    appId: '1:67132721194:ios:76f6be2fcd442113739b53',
    messagingSenderId: '67132721194',
    projectId: 'surveillance-app-ef466',
    databaseURL: 'https://surveillance-app-ef466-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'surveillance-app-ef466.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5T8hR8SXNTAmeUJwwlgBijvTlNLb-e6A',
    appId: '1:67132721194:ios:416cffa64fabee26739b53',
    messagingSenderId: '67132721194',
    projectId: 'surveillance-app-ef466',
    databaseURL: 'https://surveillance-app-ef466-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'surveillance-app-ef466.appspot.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
